### ISSUE TITLE
Binary search

### ISSUE THREAD

**Issue by ranf999** [davidxk/Algorithm-Implementations#2]
The return value of lower_bound() should be 'right', and upper_bound() should return 'left'.

**Comment by davidxk** [comment]
Please refer to C++ definition of [lower_bound](http://www.cplusplus.com/reference/algorithm/lower_bound/) and [upper_bound](http://www.cplusplus.com/reference/algorithm/upper_bound/). As commented, lower_bound is equivalent to Java ceiling or Python bisect_left; upper_bound is equivalent to Java higher or Python bisect.
